global:
  scrape_interval: 5s

  external_labels:
    stack: "apisix"

scrape_configs:

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "apisix1"
    scrape_interval: 5s
    metrics_path: "/apisix/prometheus/metrics"
    static_configs:
      - targets: ["apisix1:9091"]

  - job_name: "apisix2"
    scrape_interval: 5s
    metrics_path: "/apisix/prometheus/metrics"
    static_configs:
      - targets: ["apisix2:9091"]

  - job_name: "apisix-limit-req-exporter"
    static_configs:
      - targets: ['limit_req_exporter:8000']
    scrape_interval: 5s

  # - job_name: "redis"
  #   static_configs:
  #     - targets: ["redis:6379"]

