global:
  evaluation_interval: 30s
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "dev-prometheus"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: otel-collector
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: tempo
    scrape_interval: 5s
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          # ["x.x.x.x:9100", "x.x.x.x:9100"]
          ["node-exporter:9100"]
