apiVersion: 1
groups:
    - orgId: 1
      name: sample-group
      folder: Demo
      interval: 1m
      rules:
        - uid: ddmhkytd1jq4gc
          title: "error rate \x1Dfor 10m"
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: prometheus
              model:
                datasource:
                    type: prometheus
                    uid: prometheus
                editorMode: code
                expr: sum by (service_name) (rate(calls_total{status_code='STATUS_CODE_ERROR'}[10m]))
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 100
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: ""
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: classic_conditions
          dashboardUid: bdm8g5csol0xsb
          panelId: 3
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: bdm8g5csol0xsb
            __panelId__: "3"
            description: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
          isPaused: false
