# Base image
FROM python:3.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 라이브러리 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 스크립트 복사
COPY limit_req_exporter.py .

# 컨테이너 실행 시 실행될 명령어
CMD ["python", "limit_req_exporter.py"]