version: "3.9"

services:
  redis-node-1:
    image: redis:7.2.4
    container_name: redis-node-1
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./conf/redis-node-1.conf:/etc/redis/redis.conf
    ports:
      - "7001:7001"
      - "17001:17001" # 클러스터 노드 통신용
    networks:
      redis_ha_network:
      
  redis-node-2:
    image: redis:7.2.4
    container_name: redis-node-2
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./conf/redis-node-2.conf:/etc/redis/redis.conf
    ports:
      - "7002:7002"
      - "17002:17002"
    networks:
      redis_ha_network:

  redis-node-3:
    image: redis:7.2.4
    container_name: redis-node-3
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./conf/redis-node-3.conf:/etc/redis/redis.conf
    ports:
      - "7003:7003"
      - "17003:17003"
    networks:
      redis_ha_network:

  redis-node-4:
    image: redis:7.2.4
    container_name: redis-node-4
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./conf/redis-node-4.conf:/etc/redis/redis.conf
    ports:
      - "7004:7004"
      - "17004:17004"
    networks:
      redis_ha_network:

  redis-node-5:
    image: redis:7.2.4
    container_name: redis-node-5
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./conf/redis-node-5.conf:/etc/redis/redis.conf
    ports:
      - "7005:7005"
      - "17005:17005"
    networks:
      redis_ha_network:

  redis-node-6:
    image: redis:7.2.4
    container_name: redis-node-6
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./conf/redis-node-6.conf:/etc/redis/redis.conf
    ports:
      - "7006:7006"
      - "17006:17006"
    networks:
      redis_ha_network:

networks:
  redis_ha_network:
    driver: bridge