version: "3.9"

networks:
  default:
    name: otel-demo
    driver: bridge

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./collector/otel-config.yaml:/etc/otelcol-contrib/config.yaml
      # - ./secretkey/server.key:/etc/otelcol-contrib/server.key
      # - ./secretkey/server.crt:/etc/otelcol-contrib/server.crt
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages
    environment:
      - OTEL_COLLECTOR_GRPC_ADDR=${OTEL_COLLECTOR_GRPC_ADDR}
      - OTEL_COLLECTOR_HTTP_ADDR=${OTEL_COLLECTOR_HTTP_ADDR}
      - JAEGER_EXPORTER_PORT=${JAEGER_EXPORTER_PORT}
      - PROMETHEUS_ADDR=${PROMETHEUS_ADDR}
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "16686:16686" # Jaeger UI
      - "5778:5778" # Jaeger agent admin port
      - "4317" # grpc

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receiver
      - --enable-feature=exemplar-storage
    environment:
      - OTEL_COLLECTOR_HOST=${OTEL_COLLECTOR_HOST}
      - OTEL_COLLECTOR_METRIC_PORT=${OTEL_COLLECTOR_METRIC_PORT}
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
      - "4317" # grpc
      - "4318" # http
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - otel-collector

  node-cexporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    # command:
    #   - '--path.rootfs=/host'
    # network_mode: host
    # pid: host
    # restart: unless-stopped
    # volumes:
    #   - '/:/host:ro,rslave'
