ARG ELASTICSEARCH_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>